In [2]:
import numpy as np
import scipy as special

In [ ]:
restaurant_json_str = """
{
    "name": "Manoj",
    "surname": "Ravikumar",
    "age": 10,
    "married": true,
    "location": {
        "city": "Coimbatore",
        "state": "Tamilnadu"
    }
}
"""
print(restaurant_json_str)
import json
res_json = json.loads(restaurant_json_str)
res_str = json.dump(res_json)
print(type(restaurant_json_str),"  ", type(res_json), "   ", type(res_str))
print(res_json)
print(res_str)

In [29]:
import openmeteo_requests

import pandas as pd
import requests_cache
from retry_requests import retry

# Setup the Open-Meteo API client with cache and retry on error
cache_session = requests_cache.CachedSession('.cache', expire_after = 3600)
retry_session = retry(cache_session, retries = 5, backoff_factor = 0.2)
openmeteo = openmeteo_requests.Client(session = retry_session)

# Make sure all required weather variables are listed here
# The order of variables in hourly or daily is important to assign them correctly below
url = "https://api.open-meteo.com/v1/forecast"
params = {
	"latitude": 10.9467893,
	"longitude": 76.9859651,
	"hourly": "temperature_2m",
}
responses = openmeteo.weather_api(url, params=params)

# Process first location. Add a for-loop for multiple locations or weather models
response = responses[0]
print(f"Coordinates: {response.Latitude()}°N {response.Longitude()}°E")
print(f"Elevation: {response.Elevation()} m asl")
print(f"Timezone difference to GMT+0: {response.UtcOffsetSeconds()}s")

# Process hourly data. The order of variables needs to be the same as requested.
hourly = response.Hourly()
hourly_temperature_2m = hourly.Variables(0).ValuesAsNumpy()

hourly_data = {"date": pd.date_range(
	start = pd.to_datetime(hourly.Time(), unit = "s", utc = True),
	end = pd.to_datetime(hourly.TimeEnd(), unit = "s", utc = True),
	freq = pd.Timedelta(seconds = hourly.Interval()),
	inclusive = "left"
)}

hourly_data["temperature_2m"] = hourly_temperature_2m

hourly_dataframe = pd.DataFrame(data = hourly_data)
print("\nHourly data\n", hourly_dataframe)

Coordinates: 11.0°N 77.0°E
Elevation: 393.0 m asl
Timezone difference to GMT+0: 0s

Hourly data
                          date  temperature_2m
0   2025-09-14 00:00:00+00:00       22.612501
1   2025-09-14 01:00:00+00:00       22.612501
2   2025-09-14 02:00:00+00:00       23.812500
3   2025-09-14 03:00:00+00:00       25.712500
4   2025-09-14 04:00:00+00:00       27.512501
..                        ...             ...
163 2025-09-20 19:00:00+00:00       23.612501
164 2025-09-20 20:00:00+00:00       23.462500
165 2025-09-20 21:00:00+00:00       23.312500
166 2025-09-20 22:00:00+00:00       23.062500
167 2025-09-20 23:00:00+00:00       22.812500

[168 rows x 2 columns]


In [35]:

np.random.seed(16)
x=np.random.randint(0,10,(3,4))
print(x)

[[9 9 5 1]
 [4 4 9 0]
 [0 8 2 4]]


In [36]:
x[:2,:3]

array([[9, 9, 5],
       [4, 4, 9]])

In [40]:
x[:3,1::2]

array([[9, 1],
       [4, 0],
       [8, 4]])

In [41]:
x[::-1,::-1]

array([[4, 2, 8, 0],
       [0, 9, 4, 4],
       [1, 5, 9, 9]])

In [43]:
x[::,::-1]

array([[1, 5, 9, 9],
       [0, 9, 4, 4],
       [4, 2, 8, 0]])

In [47]:
x[:2,:2]

array([[9, 9],
       [4, 4]])

In [49]:
np.concatenate([x,x])


array([[9, 9, 5, 1],
       [4, 4, 9, 0],
       [0, 8, 2, 4],
       [9, 9, 5, 1],
       [4, 4, 9, 0],
       [0, 8, 2, 4]])

In [65]:
np.vstack([x,x[:2,:]])

array([[9, 9, 5, 1],
       [4, 4, 9, 0],
       [0, 8, 2, 4],
       [9, 9, 5, 1],
       [4, 4, 9, 0]])

In [62]:
x[:,:2]

array([[9, 9],
       [4, 4],
       [0, 8]])

In [86]:
y1,y2,y3=np.split(x,[3,3])
x

array([[9, 9, 5, 1],
       [4, 4, 9, 0],
       [0, 8, 2, 4]])

In [87]:
y1

array([[9, 9, 5, 1],
       [4, 4, 9, 0],
       [0, 8, 2, 4]])

In [88]:
y2

array([], shape=(0, 4), dtype=int64)

In [89]:
y3

array([], shape=(0, 4), dtype=int64)

In [90]:
grid = np.arange(16).reshape(4,4)

In [91]:
u,l = np.vsplit(grid,[2])

In [92]:
print(u)

[[0 1 2 3]
 [4 5 6 7]]


In [93]:
print(l)

[[ 8  9 10 11]
 [12 13 14 15]]


In [94]:
u2,l2 = np.hsplit(grid,[2])

In [95]:
print(u2)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


In [96]:
print(l2)

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [115]:
parts = np.hsplit(np.arange(16).reshape(4,4),[1,3])

In [116]:
type(parts)

list

In [117]:
parts

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [120]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)


big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

604 ms ± 4.47 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [123]:
import logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    handlers=[  # <-- plural
        logging.StreamHandler(), 
        logging.FileHandler("my_log.log", mode="w")
    ]
)

logger = logging.getLogger("ABC_App")
logger.setLevel(logging.INFO)

logger.info("INFO logs")

2025-09-14 22:56:56,720 - ABC_App - INFO - INFO logs


### SELECTING

In [9]:
x2=np.arange(28).reshape(4,7)

print("\n\nx2 is \n",x2)

## First Column
print("\n\nFirst Column is \n",x2[:,0])

## First Row
print("\n\nFirst Row is \n",x2[0:])

## 2 rows, 3 cols
print("\n\nSelect 2 rows x 3 cols is \n", x2[:2,:3])

## 3 rows, 1 to 4 cols
print("\n\nSelect 3 rows x 1 to 4 cols is \n", x2[:3,1:4])




x2 is 
 [[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]


First Column is 
 [ 0  7 14 21]


First Row is 
 [[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]


Select 2 rows x 3 cols is 
 [[0 1 2]
 [7 8 9]]


Select 3 rows x 1 to 4 cols is 
 [[ 1  2  3]
 [ 8  9 10]
 [15 16 17]]


### STACKING

In [41]:
hstack1 = np.hstack((x2,x2[:,3:4]))
print("\n\n horizontal stacking 3rd column to right ie ", x2.shape," to ", hstack1.shape ,"\n\n", hstack1)



 horizontal stacking 3rd column to right ie  (4, 7)  to  (4, 8) 

 [[ 0  1  2  3  4  5  6  3]
 [ 7  8  9 10 11 12 13 10]
 [14 15 16 17 18 19 20 17]
 [21 22 23 24 25 26 27 24]]


In [42]:
vstack1 = np.vstack((x2,x2[1:2,:]))
print("\n\n vertical stacking 2nd row to bottom ie ", x2.shape," to ", vstack1.shape ,"\n\n", vstack1)



 vertical stacking 2nd row to bottom ie  (4, 7)  to  (5, 7) 

 [[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [ 7  8  9 10 11 12 13]]


### AXIS LEVEL STACKING - 2d to 3d

In [49]:
a = np.ones((4,7))
b = np.zeros((1,7))
out = np.vstack((a,b))
print(out.shape) # (5,7)


a = np.ones((4,7))
b = np.zeros((4,7))
out = np.stack((a,b), axis=0)
print(out.shape)   # (2, 4, 7)

(5, 7)
(2, 4, 7)


In [50]:
repeated_x2_row = np.repeat(x2[2:3, :], x2.shape[0], axis=0)
fstack1 = np.stack((x2, repeated_x2_row), axis=1)

print("\n\n axis=1 stacking after padding axis=0 ie ", x2.shape," to ", fstack1.shape ,"\n\n", fstack1)



 axis=1 stacking after padding axis=0 ie  (4, 7)  to  (4, 2, 7) 

 [[[ 0  1  2  3  4  5  6]
  [14 15 16 17 18 19 20]]

 [[ 7  8  9 10 11 12 13]
  [14 15 16 17 18 19 20]]

 [[14 15 16 17 18 19 20]
  [14 15 16 17 18 19 20]]

 [[21 22 23 24 25 26 27]
  [14 15 16 17 18 19 20]]]


In [53]:
repeated_x2_col = np.repeat(x2[:, 2:3], x2.shape[1], axis=1)
fstack2 = np.stack((x2, repeated_x2_col), axis=0)

print("\n\n axis=0 stacking after padding axis=1 ie ", x2.shape," to ", fstack2.shape ,"\n\n", fstack2)



 axis=0 stacking after padding axis=1 ie  (4, 7)  to  (2, 4, 7) 

 [[[ 0  1  2  3  4  5  6]
  [ 7  8  9 10 11 12 13]
  [14 15 16 17 18 19 20]
  [21 22 23 24 25 26 27]]

 [[ 2  2  2  2  2  2  2]
  [ 9  9  9  9  9  9  9]
  [16 16 16 16 16 16 16]
  [23 23 23 23 23 23 23]]]


In [52]:
x2_cols = np.repeat(x2, x2.shape[1], axis=1)          # (4, 49)
row_cols = np.repeat(x2[2:3, :], x2.shape[1], axis=1) # (1, 49)
row_cols_tiled = np.repeat(row_cols, x2.shape[0], axis=0)  # (4, 49)
fstack2 = np.stack((x2_cols, row_cols_tiled), axis=0)      # (2, 4, 49)

print("\n\n axis=0 stacking after padding axis=1 ie ", x2.shape," to ", fstack2.shape ,"\n\n", fstack2)



 axis=0 stacking after padding axis=1 ie  (4, 7)  to  (2, 4, 7) 

 [[[ 0  1  2  3  4  5  6]
  [ 7  8  9 10 11 12 13]
  [14 15 16 17 18 19 20]
  [21 22 23 24 25 26 27]]

 [[ 2  2  2  2  2  2  2]
  [ 9  9  9  9  9  9  9]
  [16 16 16 16 16 16 16]
  [23 23 23 23 23 23 23]]]


### SPLITTING

In [61]:
x3 = np.arange(25).reshape(5,5)

In [62]:
vparts = np.vsplit(x3,[2,3])
print("\n\n vertical split ie ", x3.shape," to ", ["".join(str(vpart.shape)) for vpart in vparts] ,"\n\n", vparts)



 vertical split ie  (5, 5)  to  ['(2, 5)', '(1, 5)', '(2, 5)'] 

 [array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])]


In [63]:
hparts = np.hsplit(x3,[1,3])
print("\n\n horizontal split ie ", x3.shape," to ", ["".join(str(hpart.shape)) for hpart in hparts] ,"\n\n", hparts)



 horizontal split ie  (5, 5)  to  ['(5, 1)', '(5, 2)', '(5, 2)'] 

 [array([[ 0],
       [ 5],
       [10],
       [15],
       [20]]), array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17],
       [21, 22]]), array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19],
       [23, 24]])]


In [67]:
v1parts = np.split(x3,[2,3],axis=0)
print("\n\n vertical split ie ", x3.shape," to ", ["".join(str(vpart.shape)) for vpart in v1parts] ,"\n\n", v1parts)



 vertical split ie  (5, 5)  to  ['(2, 5)', '(1, 5)', '(2, 5)'] 

 [array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])]


In [68]:
h1parts = np.split(x3,[1,3],axis=1)
print("\n\n horizontal split ie ", x3.shape," to ", ["".join(str(hpart.shape)) for hpart in h1parts] ,"\n\n", h1parts)



 horizontal split ie  (5, 5)  to  ['(5, 1)', '(5, 2)', '(5, 2)'] 

 [array([[ 0],
       [ 5],
       [10],
       [15],
       [20]]), array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17],
       [21, 22]]), array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19],
       [23, 24]])]


In [69]:
rand = np.random.RandomState(42)
unsort1 = rand.randint(0, 10, (4, 6))
np.sort(unsort1, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [70]:
np.sort(unsort1, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

In [73]:
x4 = np.array([7, 10, 2, 3,9,  1,11, 8, 6, 5, 13, 16, 8, 4,10, 4,12])
np.partition(x4, 9)

array([ 5,  6,  2,  3,  4,  1,  4,  7,  8,  8,  9, 10, 10, 11, 16, 13, 12])

In [79]:
x5 = np.array([7,1,6,7,5,2,7,8,1,9,5,8,7,5,2,4,3,9,2,6,2,10,3,2,0])
np.partition(x5,(4,8,12))

## kth=(4, 8, 12) 
## means: ensure the 5th smallest element (index 4) is in its correct place, 
## and the 9th smallest element (index 8) is in its correct place.
## and the 13th smallet element (index 12) is in its correct place.
##
## At index 4 (0-based) you’ll find the 5th-smallest value in x5.
## At index 8 you’ll find the 9th-smallest value in x5.
## All elements before index 4 are ≤ that 5th-smallest value.
## All elements between 4 and 8 are ≤ the 9th-smallest value.
## All elements after 8 are ≥ that 9th-smallest value.
## Within each region, the values are not necessarily sorted.
##

array([ 1,  0,  1,  2,  2,  2,  2,  2,  3,  5,  4,  3,  5,  5,  6,  6,  7,
        9,  8,  9,  8, 10,  7,  7,  7])

In [80]:
np.argsort(x5)

array([24,  1,  8,  5, 20, 18, 23, 14, 22, 16, 15,  4, 10, 13,  2, 19,  0,
        6,  3, 12,  7, 11, 17,  9, 21])

In [91]:
print("Sorted numbers by list comprehension are", ", ".join(str(x5[i]) for i in np.argsort(x5)))

Sorted numbers by list comprehension are 0, 1, 1, 2, 2, 2, 2, 2, 3, 3, 4, 5, 5, 5, 6, 6, 7, 7, 7, 7, 8, 8, 9, 9, 10


In [92]:
print("Sorted numbers by map comprehension are", ",".join(map(str, x5[np.argsort(x5)])))

Sorted numbers by map comprehension are 0,1,1,2,2,2,2,2,3,3,4,5,5,5,6,6,7,7,7,7,8,8,9,9,10


### Repeating 

In [95]:
x6=np.arange(12).reshape(3,4)

In [97]:
np.tile(x6,2)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [98]:
np.repeat(x6,2)

array([ 0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,
        8,  9,  9, 10, 10, 11, 11])

In [101]:
np.tile(x6, (2,3)) # tiles of 2x2

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [109]:
r1=np.ones(x6.shape)
r1[2:3,1:3]=3
r1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 3., 3., 1.]])

In [111]:
np.repeat(x6, r1.astype(int).ravel())

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  9,  9, 10, 10, 10, 11])

In [113]:
np.repeat(x6, r1.astype(int).ravel()).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9,  9,  9],
       [10, 10, 10, 11]])